name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Archive styles
        run: |
          zip -r Ghalactic.zip Ghalactic/

      - name: Create release
        uses: ghalactic/github-release-from-tag@v6
        with:
          makeLatest: always
          assets: |
            - path: Ghalactic.zip
